# Generated by Django 4.2.3 on 2023-08-28 11:24

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("unidades", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="unidade",
            name="nome",
        ),
    ]
