# Generated by Django 4.2.3 on 2024-01-31 13:49

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Alarme",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("nome", models.CharField(max_length=255)),
                ("data", models.DateTimeField()),
            ],
            options={
                "db_table": "alarmes",
                "ordering": ["id"],
            },
        ),
    ]
