# Generated by Django 4.2.3 on 2024-02-05 13:14

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("alarmes", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="alarme",
            table="alarmes",
        ),
    ]
