# Generated by Django 4.2.3 on 2024-02-05 13:32

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("alarmes", "0002_alter_alarme_table"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="alarme",
            options={"ordering": ["-dataAlarme"]},
        ),
    ]
