# Generated by Django 4.2.3 on 2023-08-27 22:22

from django.db import migrations, models
import django.db.models.deletion
import leituras.models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("unidades", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Leitura",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "competencia",
                    models.CharField(
                        choices=[
                            ("JAN", "Janeiro"),
                            ("FEV", "Fevereiro"),
                            ("MAR", "Março"),
                            ("ABR", "Abril"),
                            ("MAI", "Maio"),
                            ("JUN", "Junho"),
                            ("JUL", "Julho"),
                            ("AGO", "Agosto"),
                            ("SET", "Setembro"),
                            ("OUT", "Outubro"),
                            ("NOV", "Novembro"),
                            ("DEZ", "Dezembro"),
                        ],
                        max_length=3,
                    ),
                ),
                ("rgi_principal", models.CharField(max_length=100)),
                ("rgi_autonoma", models.CharField(max_length=100)),
                ("status_valvula", models.CharField(max_length=100)),
                ("data_leitura", models.DateTimeField()),
                ("leitura", models.IntegerField()),
                ("fria_quente", models.CharField(max_length=100)),
                ("imovel", models.CharField(max_length=100)),
                ("hidrometro", models.CharField(max_length=100)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "unidade",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="unidades.unidade",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Folha",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "arquivo",
                    models.FileField(upload_to=leituras.models.sheet_upload_to),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "leitura",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="leituras.leitura",
                    ),
                ),
            ],
        ),
    ]
