# Generated by Django 4.2.3 on 2023-09-24 20:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Folha",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("arquivo", models.FileField(upload_to="uploads/%Y/%m/%d/")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="Relatorio",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "verbose_name_plural": "Relatórios",
            },
        ),
        migrations.CreateModel(
            name="RelatorioEvento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("event_date", models.DateTimeField(auto_now_add=True)),
                (
                    "funcionario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="funcionarios",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "relatorio",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="eventos",
                        to="leituras.relatorio",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="RelatorioAtualizado",
            fields=[
                (
                    "relatorioevento_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="leituras.relatorioevento",
                    ),
                ),
                ("id_old", models.UUIDField(editable=False)),
                ("id_new", models.UUIDField(editable=False)),
                ("arquivo_old", models.FileField(upload_to="uploads/%Y/%m/%d/")),
                ("arquivo_new", models.FileField(upload_to="uploads/%Y/%m/%d/")),
            ],
            bases=("leituras.relatorioevento",),
        ),
        migrations.CreateModel(
            name="RelatorioCriado",
            fields=[
                (
                    "relatorioevento_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="leituras.relatorioevento",
                    ),
                ),
            ],
            bases=("leituras.relatorioevento",),
        ),
        migrations.CreateModel(
            name="RelatorioDeletado",
            fields=[
                (
                    "relatorioevento_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="leituras.relatorioevento",
                    ),
                ),
            ],
            bases=("leituras.relatorioevento",),
        ),
        migrations.CreateModel(
            name="Leitura",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("rgi_principal", models.CharField(max_length=100)),
                ("rgi_autonoma", models.CharField(max_length=100)),
                ("status_valvula", models.CharField(max_length=100)),
                ("data_leitura", models.DateTimeField()),
                ("leitura", models.IntegerField()),
                ("fria_quente", models.CharField(max_length=100)),
                ("imovel", models.CharField(max_length=100)),
                ("hidrometro", models.CharField(max_length=100)),
                (
                    "folha",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="leituras.folha"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="folha",
            name="relatorio",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="leituras.relatorio"
            ),
        ),
    ]
