# Generated by Django 4.2.3 on 2024-01-22 13:16

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("leituras", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="relatorio",
            options={"ordering": ["-created_at"], "verbose_name_plural": "Relatórios"},
        ),
    ]
