# Generated by Django 4.2.3 on 2023-08-28 01:23

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("leituras", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="leitura",
            name="competencia",
        ),
        migrations.RemoveField(
            model_name="leitura",
            name="unidade",
        ),
    ]
