# Generated by Django 4.2.3 on 2024-01-23 14:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("leituras", "0002_alter_relatorio_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="condominio",
            name="nome",
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
