# Generated by Django 4.2.3 on 2023-09-27 23:42

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("leituras", "0003_alter_folha_relatorio"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="leitura",
            options={"ordering": ["data_leitura"]},
        ),
        migrations.AlterModelOptions(
            name="relatorio",
            options={"ordering": ["created_at"], "verbose_name_plural": "Relatórios"},
        ),
    ]
