# Generated by Django 4.2.3 on 2023-10-16 00:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("leituras", "0004_alter_leitura_options_alter_relatorio_options"),
    ]

    operations = [
        migrations.RenameField(
            model_name="leitura",
            old_name="fria_quente",
            new_name="tipo",
        ),
        migrations.AddField(
            model_name="leitura",
            name="hora_leitura",
            field=models.TimeField(default="00:00:00"),
        ),
        migrations.AlterField(
            model_name="leitura",
            name="data_leitura",
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name="leitura",
            name="status_valvula",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
