# Generated by Django 4.2.3 on 2024-02-05 11:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("leituras", "0005_remove_leitura_hora_leitura_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="leitura",
            name="status_valvula",
            field=models.CharField(default="aberta", max_length=100),
        ),
    ]
