# Generated by Django 4.2.3 on 2024-02-05 12:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("leituras", "0006_alter_leitura_status_valvula"),
    ]

    operations = [
        migrations.AlterField(
            model_name="leitura",
            name="status_valvula",
            field=models.CharField(default="ABERTA", max_length=100),
        ),
    ]
